language: generic 

sudo: required
services:
  - docker


before_install:
  - docker build -t andreizanoaga/docker-react -f Dockerfile.dev .


script:
  - docker run andreizanoaga/docker-react npm run test -- --coverage