language: generic 

sudo: required
services:
  - docker


before_install:
  - docker build -t andreizanoaga/docker-react -f Dockerfile.dev .


script:
  - docker run andreizanoaga/docker-react npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-941531606814"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acces_key:
    secure: "$AWS_SECRET_KEY"